from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True, label='email')
    first_name = forms.CharField(required=True, label='first_name')
    last_name = forms.CharField(required=True, label='last_name')


    class Meta:
        model = User
        fields = ['first_name','last_name','username', 'email', 'password1', 'password2']

        def save(self, commit = True):
            user = super(UserCreationForm, self).save(commit = False)
            user.email = self.cleaned_data["email"]
            if commit:
                user.save()
            return user

class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=254)
    
    class Meta:
        model = User
        fields = ('username',  'email', 'password1', 'password2', )